codeit-sprint-part2-team10/sb01-hrbank-team10

README.md
src/main/java/com/sprint/example/sb01part2hrbankteam10/config/SwaggerConfig.java

- OPS-81
docs/OPS-81-문서-추가-및-Config-설정 -> dev
1. README 기본 문서 추가 후 프로젝트 구조 부분만 수정했습니다.
2. Swagger Config 설정을 추가했습니다.
빌드 테스트 완료했습니다.

OPS-81 docs: README.md 추가 및 Swagger Config 설정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/FileRepository.java

- OPS-82
ex) feat/login -> dev
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.

OPS-82 fix: 어노테이션-수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeCreateRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/exception/errorcode/EmployeeErrorCode.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/EmployeeMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeServiceImpl.java

- OPS-28
feature/OPS-28-create-employee -> dev
직원 생성 코드 구현을 완료하였습니다.
❗부서, 프로필, 수정 이력과 관련한 코드는 다른 도메인 개발이 완료될 때마다 수정 예정입니다.

OPS-28 feat: employee 생성 구현

---

src/main/resources/hrbank-ddl.sql

- OPS-92 
fix/OPS-92-employee_histories-필드-수정 -> dev
Employee 관련 기능 구현 중 수정자 정보가 필요없다는 것을 알게 되어 해당 필드 `changed_by` 를 삭제했습니다.
employee_histories 테이블만 수정 부탁드립니다.
빌드 테스트 완료

OPS-92 fix:employee_histories-필드-수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/DepartmentController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/DepartmentCreateRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/DepartmentDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/exception/errorcode/DepartmentErrorCode.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/DepartmentMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/DepartmentService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/DepartmentServiceImpl.java

- OPS-26
ex) feat/OPS-26-department-삭제 -> dev
ex) 부서 삭제(소속 직원 있으면 삭제x) 구현

OPS-26 feat: department 삭제 구현

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/DepartmentController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/DepartmentUpdateRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/DepartmentService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/DepartmentServiceImpl.java

- OPS-25
ex) feat/OPS-25-department-수정 -> dev
ex) 날짜 수정, 부서별 직원 수 수정, update 구현

OPS-25  feat: department 업데이트 구현

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/service/DepartmentService.java

- OPS-96
feat/OPS-96-update-수정 -> dev
로그인 시, 구글 소셜 로그인 기능을 추가했습니다.

OPS-96 fix: DepartmentDto 파라미터 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/DepartmentController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/CursorPageResponseDepartmentDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/DepartmentUpdateRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/DepartmentRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/DepartmentService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/DepartmentServiceImpl.java

- OPS-27
feat/OPS-27-get-department -> dev
id 단건 조회 구현

OPS-27 feat: department 상세 조회 구현 

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/Sb01Part2HrbankTeam10Application.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/Backup.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/Department.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/Employee.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/EmployeeHistory.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/File.java
src/main/resources/hrbank-ddl.sql

- OPS-103 
fix/OPS-103-updated_at-필드-생성 -> dev
1. 부서, 직원 테이블에 updated_at 필드가 추가 되었습니다.
2. Audit 기능을 사용하며 `@CreationTimeStamp` 가 `@CreatedDate` 로 변경되었습니다.
빌드 완료 후 부서 생성, 수정일 확인 완료하였습니다.

OPS-103 fix: ddl 및 entity 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeUpdateRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/Employee.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/EmployeeMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeServiceImpl.java

- OPS-29
feature/OPS-29-update-employee -> dev
1. update 기능을 추가하였습니다.
2. FileStorage 기능과 연결하여 프로필 생성을 완료하였습니다.
3. 프로필와 부서가 없는 경우에도 NPE를 방지하기 위한 코드를 mapper에 추가하였습니다.

OPS-29 feat: update employee

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeServiceImpl.java

OPS-30
feature/OPS-30-delete-employee -> dev
- 직원 삭제 기능이 구현되었습니다.
- 직원 삭제 시 상태 변화, 프로필 삭제 이루어집니다.

OPS-30 feat: Employee 삭제 구현

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeHistoryController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/ChangeLogDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/CursorPageResponseChangeLogDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/DiffDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeHistoryCreateRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/EmployeeHistory.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/JsonConverter.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeHistoryRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeHistoryService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeHistoryServiceImpl.java
src/test/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeHistoryRepositoryTest.java

- OPS-35
ex) feat/OPS-35-get-change-logs -> dev
- 직원 정보 수정 이력 목록 조회 기능 구현했습니다.

OPS-35 feat: EmployeeHistory 목록 조회 구현

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/DepartmentController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/exception/errorcode/DepartmentErrorCode.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/DepartmentService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/DepartmentServiceImpl.java

- OPS-106
feat/OPS-106-response-update -> dev
GlobalApiResponse 컨트롤러에 반영

OPS-106 fix: RestApiResponse 반영

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeHistoryController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeHistoryService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeHistoryServiceImpl.java

- OPS-111
ex) feat/OPS-111-get-change-logs-count -> dev
- 수정 이력 건수 조회 기능 구현했습니다.
- 직원 정보 수정 이력 상세 조회 구현은 했는데 값이 빈값으로 나옵니다.

OPS-111 feat: 수정 이력 건수 조회 기능 구현

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/FileController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/FileRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/storage/FileStorage.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/storage/impl/FileStorageImpl.java
src/test/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeRepositoryTest.java
src/test/java/com/sprint/example/sb01part2hrbankteam10/storage/impl/FileStorageImplTest.java

- OPS-32
ex) feature/OPS-32-save-file
- EmployeeRepoitoryTest 파일 주석처리
- savedFiles/backups, savedFiles/profiles 저장 경로 분리, 컨트롤러 계층에서 분리되어 저장, 다운로드 되는 거 확인
<프로필 저장>
<백업 저장 = csv 파일 저장>
<프로필 다운로드>
<백업 다운로드>

feat: backup, profile 로컬 저장소 경로 분리, 분리 저장과 다운로드

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeHistoryController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/exception/errorcode/EmployeeHistoryErrorCode.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/EmployeeHistoryMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeHistoryRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeHistoryService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeHistoryServiceImpl.java

- OPS-110
ex) feat/OPS-110-get-change-logs-diffs -> dev
- 직원 정보 수정 이력 상세 조회 구현했습니다.
- EmployeeHistoryMapper로 분리해서 정리했습니다.

ops-110 feat: 직원 정보 수정 이력 상세 조회

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeTrendDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/DashboardRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeStatusService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeStatusServiceImpl.java

- OPS-83
feature/OPS-83-get-employee-status-trend -> dev
대시보드 직원수 변동 추이 구현

feat: OPS-83 get employee status trend

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeHistoryController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeHistoryCreateRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/EmployeeHistoryMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeHistoryService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeHistoryServiceImpl.java

- OPS-114
ex) feature/OPS-114-change-log-수정 -> dev
- ChangeLog 생성 메서드 파라미터 변경 (beforeData → EmployeeCreateRequest로 교체)
- 페이지네이션 postman 테스트

OPS-114 fix: change-log 메소드 파라미터 값 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/DashboardController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeTrendDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/response/EmployeeDashboardResponse.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/BackupRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/DashboardRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeStatusService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeStatusServiceImpl.java

- OPS-85
feat/lOPS-85-get-employee-count -> dev
대시보드 구현

OPS-85 feat: get employee count

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeSearchRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/exception/errorcode/EmployeeErrorCode.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/response/RestApiResponse.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/EmployeeMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/specification/EmployeeSpecification.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeServiceImpl.java

- OPS-100, 108
feature/OPS-100-get-all-employee -> dev
1. RestApiResponse 에서 data -> content 필드명이 변경되었습니다.
2. 직원 목록 조회 기능이 구현되었습니다. (동적 쿼리 - specification 적용)
3. 프로필 로컬 파일 삭제 기능이 적용하였습니다.

OPS-100 feat:  직원 목록 조회 기능 구현

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/DepartmentController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/DepartmentUpdateRequest.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/exception/GlobalExceptionHandler.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/response/RestApiResponse.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/BackupRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeServiceImpl.java

- OPS-키값
ex) feat/login -> dev
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.

OPS-116 fix: 컨트롤러 통합 및 공통 리스폰스 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/BackupDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/Backup.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/global/exception/errorcode/BackupErrorCode.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/BackupServiceImpl.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/storage/impl/FileStorageImpl.java
src/main/resources/hrbank-ddl.sql

- OPS-38
ex) feature/OPS-38-perform-backup
- 추후작성
-추후작성

OPS-38 feat: backup 생성, 최근 backup 조회, backup 목록 조회

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/EmployeeHistoryMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeHistoryServiceImpl.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeServiceImpl.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeStatusServiceImpl.java

- OPS-117
ex) feature/OPS-117-프론트-연결-테스트 -> dev
- 프론트 연결 테스트
- EmployeeHistoryMapper 사용 안되던 코드 수정

OPS-117 fix: 프론트-연결-테스트

---

build.gradle
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/BackupController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/Backup.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/BackupMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/BackupRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/BackupServiceImpl.java
src/main/resources/hrbank-ddl.sql
src/test/java/com/sprint/example/sb01part2hrbankteam10/repository/BackupRepositoryTest.java

- OPS-120
ex) fix/OPS-120-perform-backup-재PR -> dev
- 제 이전 feature/OPS-38-perform-backup PR이 중간에 꼬인 것 같아 제 최신 파일들을 반영하지 않아서 해당 파일들 전부 다시 PR 합니다. 
추후수정

fix: backup 관련 파일 전부 다시 PR

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/specification/EmployeeSpecification.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeServiceImpl.java

OPS-126
fix/OPS-126-Employee-삭제-문제-해결 -> dev
1. 프로필이 없는 직원 삭제 시 발생하는 오류를 해결하였습니다.
2. 부서명으로 검색 시 발생하는 오류를 해결하였습니다.
프론트를 통한 테스트가 완료되었습니다.

OPS-126 fix: Employee 삭제 문제 해결

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeHistoryController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/docs/EmployeeHistoryDocs.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/mapper/EmployeeHistoryMapper.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeHistoryRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeHistoryService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeHistoryServiceImpl.java

- OPS-128
ex) feature/OPS-128-test-fix -> dev
- create 문제 해결했습니다.
- 직원 상세 정보 조회 해결했습니다.

OPS-118 fix: EmployeeHistory 테스트 버그 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/DepartmentController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/EmployeeDistributionDto.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/DashboardRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/DepartmentRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/repository/EmployeeRepository.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/EmployeeStatService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/DepartmentServiceImpl.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeStatServiceImpl.java

- OPS-127
ex) feat/login -> dev
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.

OPS-127 fix: department 생성 오류 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/BackupController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/DepartmentController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/EmployeeHistoryController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/FileController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/docs/BackupDocs.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/docs/DepartmentDocs.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/docs/EmployeeDocs.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/docs/EmployeeHistoryDocs.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/docs/FileDocs.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeHistoryServiceImpl.java

- OPS-136
ex) feature/OPS-136-swagger-api-문서작성 -> dev
- swagger api 문서작성(예외처리 부분 미완성, 부족한 부분 검토 필요)
- 예외처리 value 부분 못 찾아서 " "으로 둔 곳 많습니다.

OPS-136 feat: swagger api 문서작성

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/EmployeeServiceImpl.java

OPS-138
fix/OPS-138-Employee-수정-이슈 -> dev
직원 수정 부분 오류 수정했습니다.
프론트 테스트 완료했습니다.

OPS-138 fix: Employee-수정-이슈

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/BackupController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/docs/BackupDocs.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/dto/CursorPageResponseBackupDto.java

- OPS-140
ex) refoctor/OPS-140-CursorPageResponseBackupDto-추가 -> dev
- API 스펙에 맞게 응답값 DTO로 수정

refactor: backup 목록 조회 반환값 DTO로 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/BackupServiceImpl.java

- OPS-키값
ex) 정렬수정 -> dev
- 시작시간 / 종료시간 없는 경우 (건너뜀, 진행중) 종료시간 기주 정렬이 뒤죽박죽이더 것 ->  id 기준으로 정렬되도록 수정

fix: backup 정렬 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/entity/Department.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/DepartmentServiceImpl.java

- OPS-144
ex) feature/OPS-144-update-수정 -> dev
ex) 부서 업데이트 오류 수정

OPS-144 fixupdate 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/api/BackupController.java

- OPS-146
ex) fix/OPS-146-backup-최초수행-수정 -> dev
- 대시보드에 백업 시간을 표시할 때 status 중 가장 최근 백업 이력을 가져와서 표시하는데, 백업 이력이 없을 때는 에러가 떠서 수정 -> status가 null일 때 처리
-

fix: backup status null일 때 오류 처리

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/global/exception/errorcode/BinaryContentErrorCode.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/storage/impl/BinaryContentStorageImpl.java

- OPS-147
ex) fix/OPS-147-프로필-확장자검증-추가 -> dev
- 프로필 이미지 파일만 등록할 수 있게 확장자 검사 추가

fix: 프로필 확장자 검증 추가

---

src/main/resources/application-dev.yml
src/main/resources/application-prod.yml

OPS-149
fix/OPS-149-인프라-설정 -> dev
환경 변수 관련해서 수정했습니다..
정상 동작

OPS-149 fix: 인프라 설정

---

src/main/resources/application-prod.yml

OPS-149
chore/OPS-149-DB-인프라-설정 -> dev
- 환경 변수명 중복 문제로 수정

OPS-149 chore: DB 인프라 설정 수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/view/MainController.java
src/main/resources/application.yml

OPS-151
fix/OPS-151-ViewController-수정 -> dev
컨트롤러 /dashboard 추가

OPS-151 fix: ViewController수정

---

src/main/resources/application.yml

OPS-152
chore/OPS-152-프로필수정 -> dev
프로필 설정 변경

OPS-152 chore:프로필수정

---

src/main/java/com/sprint/example/sb01part2hrbankteam10/config/scheduler/BackupScheduler.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/controller/api/BackupController.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/BackupService.java
src/main/java/com/sprint/example/sb01part2hrbankteam10/service/impl/BackupServiceImpl.java

- OPS-148
ex) fix/OPS-148-backup-batch-수정 -> dev
- 수동 백업 작업자명 IP 받아오도록 다시 수정
- 테스트 완료

fix: 수동 backup 작업자명 수정, batch 수정
